### ISSUE TITLE
spec

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/EU4JPModAppendixII#1]
- paratranzからダウンロードしたエスケープ済みのhistoryとcommonを含める
- 上記以外のファイルに対しても、名前変更などを行ってからエスケープしたファイルを含める。具体的な処理は下記。
https://github.com/matanki-saito/paradox_util/tree/master/replacename

**Comment by oooFUNooo** [comment]
現在ローカルでは`common/countries`以下のファイルに対して、さらに次の追加処理を行っています。

- 東アジアの特定の国の人名から序数（`#0, #1, ...`）を削除する。
- 東アジアの特定の国の指揮官の姓名を逆転させる（逆疑問符をつける）

両方とも自動変換スクリプトがあり、処理すべきの国のリストは別ファイルで管理しています。
必要であればご提供しますので、お申し付けください。

**Comment by matanki-saito** [comment]
ありがとうございます。
上記２つの処理はparatranzの翻訳には反映するのが難しかったでしたか？たしか記憶では50件程度であったと思います。
人力で反映できるのであれば、この際やってしまいたいです。

**Comment by oooFUNooo** [comment]
ParaTranzの翻訳に反映することはできません。これは手動でも同じことです。
なぜなら、ParaTranz上で同じキーを持つ人物（=同名の人物）が複数登録されているからです。
以前、chatnoir17氏が出現頻度に偏りを持たせるため、意図的にそうしていると発言していました。
この問題を最終的に解決するためには、ParaTranz自体の仕様を変えてもらうしかないと思われます。

また、遠からずEU4のアップデートで日本の人名が一新されることも示唆されています。
現時点で手間をかけて修正しても、すぐに陳腐化することは目に見えています。

**Comment by matanki-saito** [comment]
ありがとうございます、Discordで少し相談させてください

**Comment by oooFUNooo** [comment]
東アジアの特定の国リストです。
[list.txt](https://github.com/matanki-saito/EU4JPModAppendixII/files/2995155/list.txt)

**Comment by matanki-saito** [comment]
Aの段、終了しました。
x Ainu.txt
x Akamatsu.txt
x Amago.txt
x Ando.txt
x Asakura.txt
x Ashikaga.txt

**Comment by matanki-saito** [comment]
終了
x Changsheng.txt

**Comment by matanki-saito** [comment]
rate limitに引っかかるようになってきましたので、また明日～

**Comment by matanki-saito** [comment]
x Chiba.txt
x Chosokabe.txt

**Comment by matanki-saito** [comment]
x Date.txt
x Hatakeyama.txt
x Hojo.txt

**Comment by matanki-saito** [comment]
x Toki.txt
x Hosokawa.txt
x Kikuchi.txt
x Isshiki.txt
x Ito.txt
x Korea.txt

**Comment by matanki-saito** [comment]
x Imagawa.txt
x MongolEmpire.txt
x Ikeda.txt
x Kitabatake.txt
x Kono.txt
x Mori.txt
x Ouchi.txt

**Comment by matanki-saito** [comment]
x Ryukyu.txt
x Satake.txt
x Shiba.txt
x Shimazu.txt
x Nanbu.txt
x Oda.txt

**Comment by matanki-saito** [comment]
x Ogasawara.txt
x Otomo.txt
x Maeda.txt
x Japan.txt
x Tokugawa.txt
x Tsutsui.txt

**Comment by matanki-saito** [comment]
x Uesugi.txt
x Utsunomiya.txt
x Yamana.txt
x Takeda.txt

**Comment by matanki-saito** [comment]
残り
Chu.txt
Dali.txt
Huai.txt
Jin.txt
Liang.txt
Miao.txt
Min.txt
Ming.txt
Ning.txt
Qi.txt
Qin.txt
Qing.txt
Shoni.txt
Shu.txt
Shun.txt
Tang.txt
Wu.txt
Xi.txt
Yan.txt
Yi.txt
Yue.txt
Zhou.txt

**Comment by matanki-saito** [comment]
x Chu.txt
x Ming.txt
x Dali.txt
x Huai.txt
x Ning.txt
x Liang.txt
x Miao.txt
x Jin.txt
x Zhou.txt
x Shun.txt
x Shoni.txt
x Tang.txt
x Xi.txt
x Yi.txt
x Yue.txt
x Qing.txt
x Min.txt
x Qi.txt
x Qin.txt
x Shu.txt
x Wu.txt
x Yan.txt

**Comment by matanki-saito** [comment]
残り
ー

**Comment by matanki-saito** [comment]
Lanfangも処理する必要がありますか？
https://paratranz.cn/projects/76/strings?file=11849&anchor=5268843&page=1

**Comment by matanki-saito** [comment]
Lanfang処理しました。
確認も終了したためCloseします
