### ISSUE TITLE
Not working event

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/EU4JPModAppendixII#2]
致命的なバグが発見されました。
固有名詞 Sub Modを使用している場合、イングランドの国難「薔薇戦争」が正常に動作しません。
ーーーー
推測される原因：
国難の条件に王朝名（ランカスター家、ヨーク家）が影響を与えるにも関わらず、
関連する以下のファイルが日本語化Modに含まれていない（＝日本語化されていない）
common/disasters/war_of_the_roses.txt
events/disaster_ENG_WarOfTheRoses.txt
ーーーー
推測される影響範囲：
固有名詞 Sub Modを使用している全ユーザー。
現在の配布方式で一番古い5月3日のデータまで遡りましたが、上記ファイルは含まれていませんでした。
ParaTranzで王朝名が日本語に訳されたのは8ヶ月前で、最悪の場合、8ヶ月前からある問題ということになります。
ーーーー
簡単な確認方法：
固有名詞 Sub Modをオンにして、1444年のイングランドで開始し、左上の国難アラートにマウスを合わせる。
王朝名が表示されるべき場所に「nodynasty」と表示されている（左の引用符が欠けているのは別の問題）
![War_of_the_Roses](https://user-images.githubusercontent.com/35730970/62218958-6a606e80-b3e8-11e9-8065-d31e78e9d4cb.jpg)
なお、報告されている症状は、国難が発生した後、即座に終了するというものです。
上記の関連ファイルだけで問題が解決するとは限りません。
同様に、上記の簡単な確認方法だけでは、症状が解決したことの確認にはなりません。

**Comment by oooFUNooo** [comment]
色々実験した結果をまとめます。

実験方法：
`common/disasters/war_of_the_roses.txt`の`dynasty =`の右辺を書き換えて、
国難のアラートに「nodynasty」と表示されるかどうかを確認する。

実験結果：
以下の説明において、
無効とは「nodynasty」と表示される場合、
有効とは「nodynasty」と表示されず王朝名が正しく表示される場合を意味する。

・実在しない王朝名は無効（例、TEST、ABCDE）
・ゲーム開始時に存在する王朝名は有効（例、de Valois、Oda、Tokugawa）
・ゲーム開始時に存在しない王朝名でも定義されていれば有効（例、Toyotomi、Mori、Ryuzoji）
・TESTという王朝名でも `history/countries/*` に追加すれば有効になる
・日本語化された王朝名は `history/countries/*` に存在しても無効になる

結論：
・王朝名が有効かどうかは `history/countries/*` に定義が存在するかどうかで決まる
・`dynasty =` の右辺を日本語化しても王朝名としては認識されない
・王朝名を引用符で囲んでも囲まなくても結果は変わらない

**Comment by oooFUNooo** [comment]
原因を完全に特定しました。

問題の薔薇戦争終結イベントは`events/disaster_ENG_WarOfTheRoses.txt`の1220行以降にあり、
「ランカスター家でもヨーク家でもない第三の勢力が戦争を終わらせた」という状況で発生します。

イベント発生のトリガーは次のようになっています。
```
    trigger = {
        tag = ENG
        has_disaster = war_of_the_roses
        NOT = { dynasty = York }
        NOT = { dynasty = Lancaster }
    }
```

現在のイングランドの王朝がYorkでもLancasterでもない場合に発生するので、
王朝名だけが日本語化されていて、このスクリプトが日本語化されていないと、
薔薇戦争が始まった直後に、この終了イベントが発生することになります。

以上の事実より、この不具合を修正するためには、当初の見込み通り、
`common/disasters/war_of_the_roses.txt`
`events/disaster_ENG_WarOfTheRoses.txt`
の2ファイルを日本語化する必要があります。

**Comment by matanki-saito** [comment]
こちらで改修終了したためクローズします。
https://github.com/matanki-saito/EU4JPModAppendixII/commit/f912f64a8c107497ac12383472549a303e82eb2f
